### ISSUE TITLE
Presentation -- enable vertical navigation

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#595] opened 2021-02-16 06:32 UTC
When expanding a bullet, often part of the content is not visible. Reveal.js has vertical navigation but it works for defined slides. In the case of Roam Presentation, it needs to work more like page down/up.

**Comment by dvargas92495** [comment] 2021-02-16 15:33
duplicate of https://github.com/dvargas92495/roam-js-extensions/issues/585?

**Comment by kvistgaard** [comment] 2021-02-16 20:54
Indeed but might be interpreted differently, so if the two descriptions are merged into the same enhancement to clarify the scope (might be two different parameters to enable diff behaviour -- step/slide per bullet vs page down), I'd be happy to support it.

**Closed** 2021-02-16 21:53 UTC
